config/routes.rb
Rails.application.routes.draw do
  root "quests#index"
  get "/quests", to: redirect("/")
  resources :quests, only: [ :create, :update, :destroy ]
  get "/brag", to: "quests#brag"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quest.rb
class Quest < ApplicationRecord
  attribute :completed, :boolean, default: false

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :set_quest, only: [ :update, :destroy ]

  def index
    @quests = Quest.all
    @new_quest = Quest.new
  end

  def create
    @new_quest = Quest.new(quest_params)
    if @new_quest.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def update
    @quest.update(completed: !@quest.completed)
    redirect_to root_path
  end

  def destroy
    @quest.destroy
    redirect_to root_path
  end

  def brag
  end

  private
    def quest_params
      params.require(:quest).permit(:title)
    end

    def set_quest
      @quest = Quest.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "My Academy Quest" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mb-16 px-5 max-w-xl">
      <%= yield %>
    </main>
  </body>
</html>

app/views/quests/_card.html.erb
<li class="list-row flex justify-between items-center gap-2">
  <%= form_with url: quest_path(quest), method: :patch, local: true, class: "flex-1 flex items-center justify-start gap-2 w-auto" do |form| %>
    <%= form.check_box :completed, checked: quest.completed, class: "checkbox", onchange: "this.form.submit()" %>
    <%= form.label :title, quest.title, class: "max-w-4/5 font-bold text-lg md:text-xl #{quest.completed && 'line-through'}" %>
  <% end %>

  <%= button_to "Remove", quest_path(quest), method: :delete, class: "btn btn-sm btn-error", data: { confirm: "Are you sure?" } %>
</li>

app/views/quests/brag.html.erb
<header class="mb-4 mt-16">
  <%= link_to "< Back to My Quests", root_path, class: "hover:cursor-pointer text-primary" %>
  <h1 class="font-bold text-xl sm:text-3xl">Fame's Brag Document</h1>
</header>

<div class="card bg-info/10 shadow-sm p-4">
  <h2 class="sm:font-bold text-base">เป้าหมายในปีนี้ (2025)</h2>

  <ul class="list-disc pl-5">
    <li>อยากพัฒนาทักษะสกิล UX/UI, testing, และ DevOps ให้สามารถช่วยแก้ปัญหาที่คนอื่น ๆ หรือตัวเองเจอได้</li>
    <li>เริ่มใช้ TDD ในการทำโจทย์ programming ให้มากขึ้น</li>
    <li>เริ่มอ่าน text book ให้จบอย่างน้อย 1 เล่ม ต่อเดือน</li>
    <li>ออกกำลังกายให้ได้ 2-3 วันต่อสัปดาห์</li>
    <li>ฝึกภาษาอังกฤษให้สามารถพูดในชีวิตได้</li>
  </ul>
</div>

<div class="divider"></div>

app/views/quests/index.html.erb
<header class="text-center pt-16">
  <div class="card card-side shadow-sm">
    <figure class="w-40 sm:w-48">
      <%= image_tag "my-profile.jpg", alt: "Fame's Quest Image", class: "" %>
    </figure>
    <div class="card-body justify-end sm:justify-between">
      <div>
        <h1 class="font-bold text-xl sm:text-3xl text-start">Fame's Quest</h1>
        <h6 class="sm:font-bold text-md text-start">Phuwamet Panjachalermrat</h6>
      </div>

      <div class="card-actions justify-end">
        <%= link_to "Fame's Brag Document", brag_path, class: "btn btn-info mt-4" %>
      </div>
    </div>
  </div>

  <div class="divider"></div>
</header>

<section class="sticky top-0 z-10 bg-white sm:pt-2 pb-2">
  <%= form_with class: "flex justify-between flex-col sm:flex-row gap-2 sm:gap-4", model: @new_quest, url: quests_path do |form| %>
    <%= form.text_field :title, placeholder: "Enter quest title", class: "input w-full" %>
    <%= form.submit "Create Quest", class: "btn btn-primary" %>
  <% end %>
</section>

<main>
  <% if @quests.any? %>
    <ul class="list min-h-full w-full px-4 pt-2 overflow-hidden">
      <% @quests.each do |quest| %>
        <%= render 'card', quest: quest %>
      <% end %>
    </ul>
  <% else %>
    <p class="w-full py-2 text-xl font-bold text-center">No quests available.</p>
  <% end %>
</main>